USE [master]
GO
CREATE DATABASE [panstwa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'panstwa-db', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\panstwa-db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'panstwa-db_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\panstwa-db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [panstwa] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [panstwa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [panstwa] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [panstwa] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [panstwa] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [panstwa] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [panstwa] SET ARITHABORT OFF 
GO
ALTER DATABASE [panstwa] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [panstwa] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [panstwa] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [panstwa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [panstwa] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [panstwa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [panstwa] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [panstwa] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [panstwa] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [panstwa] SET  DISABLE_BROKER 
GO
ALTER DATABASE [panstwa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [panstwa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [panstwa] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [panstwa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [panstwa] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [panstwa] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [panstwa] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [panstwa] SET RECOVERY FULL 
GO
ALTER DATABASE [panstwa] SET  MULTI_USER 
GO
ALTER DATABASE [panstwa] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [panstwa] SET DB_CHAINING OFF 
GO
ALTER DATABASE [panstwa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [panstwa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [panstwa] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [panstwa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'panstwa', N'ON'
GO
ALTER DATABASE [panstwa] SET QUERY_STORE = OFF
GO
USE [panstwa]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Panstwo](
	[ID] [int] NOT NULL,
	[NazwaPowszechna] [varchar](30) NULL,
	[NazwaOficjalna] [varchar](60) NULL,
	[KodISO3166] [varchar](3) NULL,
	[TypRzaduID] [int] NOT NULL,
	[LiczbaObywateli] [int] NULL,
	[HDI] [float] NULL,
	[URLflagi] [varchar](256) NULL,
 CONSTRAINT [PK_Panstwo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleId] [int] NOT NULL,
	[RoleName] [varchar](32) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TypRzadu](
	[ID] [int] NOT NULL,
	[Nazwa] [varchar](40) NULL,
 CONSTRAINT [PK_TypRzadu] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRole](
	[Id] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
 CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] NOT NULL,
	[Login] [varchar](64) NOT NULL,
	[PasswordHash] [varbinary](max) NOT NULL,
	[AddTime] [datetime] NOT NULL,
	[PasswordSalt] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Panstwo]  WITH NOCHECK ADD  CONSTRAINT [FK_Panstwo_TypRzadu] FOREIGN KEY([TypRzaduID])
REFERENCES [dbo].[TypRzadu] ([ID])
GO
ALTER TABLE [dbo].[Panstwo] CHECK CONSTRAINT [FK_Panstwo_TypRzadu]
GO
ALTER TABLE [dbo].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_Roles] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([RoleId])
GO
ALTER TABLE [dbo].[UserRole] CHECK CONSTRAINT [FK_UserRole_Roles]
GO
ALTER TABLE [dbo].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[UserRole] CHECK CONSTRAINT [FK_UserRole_Users]
GO
USE [master]
GO
ALTER DATABASE [panstwa] SET  READ_WRITE 
GO